---
title: "Sankey plot cell types MOFA"
output:
  pdf_document: default
  html_notebook: default
---

### clean environment
```{r}
rm(list=ls())
```

### set directory (replace by your path)
```{r setup}
    knitr::opts_knit$set(root.dir = normalizePath("/home/flomik/Code/MOFA_AML")) 
```

```{r}
library(MultiAssayExperiment)
library(MOFA2)
library(RColorBrewer)
library(GSEABase)
library(tidyverse)
library(minfi)
library(xlsx)
library(org.Hs.eg.db)
library(maditr)
library(ggalluvial)
```

# Analysis

## load cell types
```{r}
cells <- read.csv("processing/cell_types_genes.txt", row.names = 1)
cells <- data.frame(t(cells))
cells$Genes <- rownames(cells)
```


## load enrichment pvalues
```{r}
cell_neg <- read.csv("data/server/cell_types_top_pathways_tojo_negative.csv", row.names = 1)
row_names <- rownames(cell_neg)
cell_neg_2  <- stack(cell_neg)
cell_neg_2$ind_2 <- rep(row_names, ncol(cell_neg))
cell_neg_2$sign <- "neg"
cell_neg_2$type <- "cell-factor"

cell_pos <- read.csv("data/server/cell_types_top_pathways_tojo_positive.csv", row.names = 1)
row_names <- rownames(cell_pos)
cell_pos_2  <- stack(cell_pos)
cell_pos_2$ind_2 <- rep(row_names, ncol(cell_pos))
cell_pos_2$sign <- "pos"
cell_pos_2$type <- "cell-factor"
```

```{r}
cell_type <- rbind(cell_pos_2, cell_neg_2)
cell_type <- cell_type[!is.na(cell_type$values),]
cell_type$ind <- gsub("Factor", "DDHM", cell_type$ind)
cell_type <- cell_type[order(cell_type$sign, cell_type$values),]
cell_type$ind_2 <- factor(as.vector(cell_type$ind_2), levels = as.vector(cell_type$ind_2)[!duplicated(cell_type$ind_2)])
```

```{r}
cell_type_filt <- cell_type[!grepl("100", cell_type$ind_2),]
```

```{r}
cell_type_filt$Pathway <- as.vector(cell_type_filt$ind_2)
cell_type_filt$Pathway <- gsub("\\.Top250", "", cell_type_filt$Pathway)
```

```{r}
cell_type_filt_pos <- cell_type_filt[cell_type_filt$sign == "pos",]
cell_type_filt_pos$values <- NULL
cell_type_filt_pos$sign <- NULL
cell_type_filt_pos$ind_2 <- NULL
cell_type_filt_pos$type <- NULL
colnames(cell_type_filt_pos)[2] <- "Cell_P"
```

```{r}
cell_type_filt_neg <- cell_type_filt[cell_type_filt$sign == "neg",]
cell_type_filt_neg$values <- NULL
cell_type_filt_neg$sign <- NULL
cell_type_filt_neg$ind_2 <- NULL
cell_type_filt_neg$type <- NULL
colnames(cell_type_filt_neg)[2] <- "Cell_N"
```


```{r}
data <- merge(cell_type_filt_pos, cell_type_filt_neg, by = "ind", all.x = TRUE, all.y = TRUE)
data$Freq <- 1
data$Cell_N[data$Cell_N == "LSC104_Ng2017_DOWN"] <- "LSC(down)"
data$Cell_N[data$Cell_N == "MLL_LSC_Somervaille2009_Up"] <- "MLL_LSC(up)"
data$Cell_N[data$Cell_N == "MLL_LSC_Somervaille2009_Down"] <- "MLL_LSC(down)"


data$Cell_P[data$Cell_P == "LSC104_Ng2017_DOWN"] <- "LSC(down)"
data$Cell_P[data$Cell_P == "MLL_LSC_Somervaille2009_Up"] <- "MLL_LSC(up)"
data$Cell_P[data$Cell_P == "MLL_LSC_Somervaille2009_Down"] <- "MLL_LSC(down)"
```

```{r}
col_mofa <- c("#584588",
"#4076A9",
"#ABCADA",
"#BED797",
"#5E9F48",
"#F1EFB3",
"#EEC17F",
"#E88840",
"#E99D9B",
"#CE3D31",
"#BCB2C9")
```

```{r}
table(data$ind)
```

```{r}
data$ind <- factor(data$ind, levels = paste0("DDHM", 1:11))
```

```{r}
x <- data.frame(table(data$ind))
x
```

```{r}
for (i in 1:11) {
  factor <- paste0("DDHM", i)
  freq <- x$Freq[x$Var1 == factor]
  data$Freq[data$ind == factor] <- data$Freq[data$ind == factor]/log10(freq)
}
```

```{r}
ggplot(data = data,
       aes(axis1 = Cell_N, axis2 = ind,
           y = Freq))+
  geom_stratum(aes(fill = ind), alpha = 1)+
  geom_alluvium(aes(fill = ind), alpha = 0.7)+
  geom_text(stat = "stratum", alpha =  1, aes(label = after_stat(stratum))) +
  theme_classic()+
  scale_fill_manual(values =  col_mofa[c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11)], na.value="00FFFFFF")

ggsave("results/figures/sankey_plot_cell_types_N_Tojo_corrected.png", width = 7, height = 5)
#ggsave("results/figures/sankey_plot_cell_types_N_Tojo_corrected.pdf", width = 7, height = 5)
```

```{r}
ggplot(data = data,
       aes(axis1 = ind, axis2 = Cell_P,
           y = Freq))+
  geom_stratum(aes(fill = ind), alpha = 1)+
  geom_alluvium(aes(fill = ind), alpha = 0.7)+
  geom_text(stat = "stratum", alpha =  1, aes(label = after_stat(stratum))) +
  theme_classic()+
  scale_fill_manual(values =  col_mofa[c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10 , 11)], na.value="00FFFFFF")

ggsave("results/figures/sankey_plot_cell_types_P_Tojo_corrected.png", width = 7, height = 5)
#ggsave("results/figures/sankey_plot_cell_types_P_Tojo_corrected.pdf", width = 7, height = 5)
```

