---
title: "R Notebook"
output: html_notebook
---

### clean environment
```{r}
rm(list=ls())
```

### set directory

```{r setup}
    knitr::opts_knit$set(root.dir = normalizePath("/home/flomik/Code/MOFA_AML")) 
```

```{r}
library(readxl)
library(smplot2)
```

## extract DDHM values
```{r}
factors <- read.csv("processing/MOFA_transcriptomics_scores.csv", row.names = 1)
factors <- data.frame(factors)
```

```{r}
factors$Factor4_score <- -1*factors$Factor4_score
factors$Factor8_score <- -1*factors$Factor8_score
```


```{r}
load("data/input_files/MOFA_input/AML_MAexp_v05.RData")
drug <- data.frame(MAexp@ExperimentList@listData$DSRT@assays@data)
drug <- data.frame(t(drug[,-c(1:2)]))
drug$patient_id <- rownames(drug)

data <- merge(factors, drug, by = "patient_id")
```


```{r}
a <- ggplot(data = data, mapping = aes(x = Factor2_score, y = FIMM115484)) +
          geom_point(size = 1) + xlab("DDHM2 score") + ylab("Venetoclax response")+
          sm_statCorr(corr_method = "pearson", size = 0.1) +
  geom_smooth(method=lm, level=0.95, colour = "#4076A9", fill = "#4076A9", alpha=0.25)+
  theme_light()+ 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
                                      text=element_text(family="Helvetica", size=12))
a
ggsave("results/figures/Associations/scatter_plots_Venetoclax_vs_txn_score_2.pdf", width = 4, height = 4, units = "in")
```

FIMM003794
```{r}
a <- ggplot(data = data, mapping = aes(x = Factor4_score, y = FIMM003794)) +
          geom_point(size = 1) + xlab("DDHM4 score") + ylab("Sorafenib drug response")+
          sm_statCorr(corr_method = "pearson", size = 0.1) +
  geom_smooth(method=lm, level=0.95, colour = "#BED797", fill = "#BED797", alpha=0.25)+
  theme_light()+ 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
                                      text=element_text(family="Helvetica", size=12))
a
ggsave("results/figures/Associations/scatter_plots_Sorafenib_vs_txn_score_4.pdf", width = 4, height = 4, units = "in")
```
