---
title: "Change sign"
output: html_notebook
---

Aim : change sign to match original model
Compare DDHM transcriptomics with top 5 positive and negative genes from the model 

### clean environment
```{r}
rm(list=ls())
```

### set directory
```{r setup}
    knitr::opts_knit$set(root.dir = normalizePath("/home/flomik/Code/MOFA_AML/")) 
```

```{r}
library("readxl")
library("data.table")
library(dplyr)
library(Seurat)
library(ggplot2)
```

## load object
```{r}
data <- readRDS("/home/flomik/Data/CITE_seq/Seurat_object_predicted_class_BMmap_KI_with_scores_v2.rds")
data
```


## extract top feature per factor
```{r}
RNA_factors=NULL
for (i in 1:11){
  factorName=paste0("Factor",i,"_RNAseq")
  cat(factorName," ")
  dat=read_excel("/home/flomik/Code/Hallmarks_AML/data/Ngias/AML_MOFAplus_top_factors_v04_f600 (1).xlsx",sheet=factorName)
  dat=data.table(dat)
  print(nrow(dat))
  RNA_factors[[i]]=dat
}

RNAfac=do.call(rbind,RNA_factors)
RNAfac$feature=gsub(".g","",RNAfac$feature)

## set thresholds for each factor
factorNames=unique(RNAfac$factor)
topGeneThres=c(9,10,2,6,4,1,2,3,3,6,3)
names(topGeneThres)=factorNames
```

```{r}
BMmap_scores_scRNA <- read.csv("~/Code/MOFA_AML/results/scores_cells_and_factors_CITE_seq_KI_prospective.csv")
```

```{r}
list_genes_top <- list()

for (i in 1:11) {
  score_name <- paste0("Factor_", i,"_score")
  score <- BMmap_scores_scRNA[, colnames(BMmap_scores_scRNA) == score_name]
  sheet <- RNA_factors[[i]]
  pos <- sheet[sheet$sign == "+",]
  pos <- pos[order(pos$value, decreasing = TRUE),]
  top_feat <- pos$label[1:5]
  print(top_feat)
  list_genes_top[[i]] <- top_feat
}
```

## c
```{r}
for(i in 1:length(list_genes_top)){
  list_genes <- list_genes_top[[i]]
  print(list_genes)
  feat <- c(list_genes, paste0("Factor_", i, "_score"))
   FeaturePlot(data, features = feat, label = FALSE, repel = TRUE) +
            #scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdBu"))) #+ ggplot2::theme(legend.position = "none")
            scale_colour_gradient2(low = "#2166AC", mid = "#fbf6f0", high = "#B2182B", midpoint = 0, space = "Lab", na.value = "grey50", guide = "colourbar")
  ggsave(paste0("results/figures/scRNA/KI/review_score_plot_top_genes_pos_Factor_", i,"_scores_MOFA_positive.pdf"), width = 7, height = 5)
}
```

```{r}
list_genes_top <- list()

for (i in 1:11) {
  score_name <- paste0("Factor_", i,"_score")
  score <- BMmap_scores_scRNA[, colnames(BMmap_scores_scRNA) == score_name]
  sheet <- RNA_factors[[i]]
  pos <- sheet[sheet$sign == "-",]
  pos <- pos[order(pos$value, decreasing = TRUE),]
  top_feat <- pos$label[1:5]
  print(top_feat)
  list_genes_top[[i]] <- top_feat
}
```

## c
```{r}
for(i in 1:length(list_genes_top)){
  list_genes <- list_genes_top[[i]]
  print(list_genes)
  feat <- c(list_genes, paste0("Factor_", i, "_score"))
   FeaturePlot(data, features = feat, label = FALSE, repel = TRUE) +
            #scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdBu"))) #+ ggplot2::theme(legend.position = "none")
            scale_colour_gradient2(low = "#2166AC", mid = "#fbf6f0", high = "#B2182B", midpoint = 0, space = "Lab", na.value = "grey50", guide = "colourbar")
  ggsave(paste0("results/figures/scRNA/KI/review_score_plot_top_genes_pos_Factor_", i,"_scores_MOFA_negative.pdf"), width = 7, height = 5)
}
```

## change sign
```{r}
data$Factor_4_score <- -1*data$Factor_4_score
data$Factor_5_score <- -1*data$Factor_5_score
data$Factor_8_score <- -1*data$Factor_8_score
```

```{r}
FeaturePlot(data, features = "Factor_4_score", label = FALSE, repel = TRUE) +
            #scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdBu"))) #+ ggplot2::theme(legend.position = "none")
            scale_colour_gradient2(low = "#2166AC", mid = "#fbf6f0", high = "#B2182B", midpoint = 0, space = "Lab", na.value = "grey50", guide = "colourbar")
  ggsave(paste0("results/figures/scRNA/KI/review_score_plot_top_genes_pos_Factor_4_scores_MOFA_new_sign.pdf"), width = 7, height = 5)
```

```{r}
FeaturePlot(data, features = "Factor_5_score", label = FALSE, repel = TRUE) +
            #scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdBu"))) #+ ggplot2::theme(legend.position = "none")
            scale_colour_gradient2(low = "#2166AC", mid = "#fbf6f0", high = "#B2182B", midpoint = 0, space = "Lab", na.value = "grey50", guide = "colourbar")
  ggsave(paste0("results/figures/scRNA/KI/review_score_plot_top_genes_pos_Factor_5_scores_MOFA_new_sign.pdf"), width = 7, height = 5)
```


```{r}
FeaturePlot(data, features = "Factor_8_score", label = FALSE, repel = TRUE) +
            #scale_colour_gradientn(colours = rev(brewer.pal(n = 11, name = "RdBu"))) #+ ggplot2::theme(legend.position = "none")
            scale_colour_gradient2(low = "#2166AC", mid = "#fbf6f0", high = "#B2182B", midpoint = 0, space = "Lab", na.value = "grey50", guide = "colourbar")
  ggsave(paste0("results/figures/scRNA/KI/review_score_plot_top_genes_pos_Factor_8_scores_MOFA_new_sign.pdf"), width = 7, height = 5)
```
  
