---
title: "Split heatmap pathways"
output: html_notebook
---

Correlations :
- music cell types vs hallmarks
- music cell types vs hallmarks transcriptomics
### clean environment
```{r}
rm(list=ls())
```

### set directory (replace by your path)
```{r setup}
    knitr::opts_knit$set(root.dir = normalizePath("/home/flomik/Code/MOFA_AML")) 
```


```{r}
library(dplyr)
library(tidyr)
library(purrr)
library(ggplot2)
library(xlsx)
```

## function found on stackoverflow
https://stackoverflow.com/questions/65887187/how-to-display-two-categorical-variables-on-one-tile-of-a-heatmap-triangle-til
```{r}
make_triangles <- function(x, y, point = "up") {
  x <- as.integer(as.factor((x)))
  y <- as.integer(as.factor((y)))

  if (point == "up") {
    newx <- sapply(x, function(x) {
      c(x - 0.5, x - 0.5, x + 0.5)
    }, simplify = FALSE)
    newy <- sapply(y, function(y) {
      c(y - 0.5, y + 0.5, y + 0.5)
    }, simplify = FALSE)
  } else if (point == "down") {
    newx <- sapply(x, function(x) {
      c(x - 0.5, x + 0.5, x + 0.5)
    }, simplify = FALSE)
    newy <- sapply(y, function(y) {
      c(y - 0.5, y - 0.5, y + 0.5)
    }, simplify = FALSE)
  }
  data.frame(x = unlist(newx), y = unlist(newy))
}
```

/home/flomik/Code/MOFA_AML/data/Music/beat_aml_music_cell_type_broad_proportions.csv


## correlation hallmarks vs cell type
```{r}
music <- read.xlsx("/home/flomik/Code/MOFA_AML/data/Music/merged_music_cell_type_broad_mean_proportions.xlsx", 1)
names <- read.xlsx("/home/flomik/Code/MOFA_AML/data/Music/rename_table.xlsx", 1)
names$NA. <- NULL
colnames(names)[1] <- "NA."
music <- merge(music, names, by = "NA.")
music$NA. <- music$DDHMNames
music$DDHMNames <- NULL
```

```{r}
factors <- read.xlsx("/home/flomik/Code/MOFA_AML/data/MOFA/DDHMpatValue.xlsx", 1)
patients <- factors$patient_id
rownames(factors) <- factors$patient_id
factors$sample <- NULL
factors$patient_id <- NULL
factors <- data.frame(lapply(factors, as.numeric))
factors$patient_id <- patients
colnames(factors) <- gsub("DDHM", "Factor", colnames(factors))
hallmarks <- factors

hallmarks <- hallmarks[hallmarks$patient_id %in% music$NA.,]
music <- music[music$NA. %in% hallmarks$patient_id,]
colnames(music)[1] <- "patient_id"
music <- music[order(music$patient_id, hallmarks$patient_id),]

music$patient_id == hallmarks$patient_id

rownames(music) <- music$patient_id
music$patient_id <- NULL

rownames(hallmarks) <- hallmarks$patient_id
hallmarks$patient_id <- NULL
```

```{r}
txn <- read.csv("~/Code/MOFA_AML/processing/MOFA_transcriptomics_scores.csv", row.names = 1)
txn <- txn[,!grepl("group", colnames(txn))]
txn <- txn[txn$patient_id %in% rownames(music),]
txn <- txn[order(txn$patient_id, rownames(music)),]

rownames(music) == txn$patient_id
txn$patient_id <- NULL

colnames(txn) <- gsub("_score", "",colnames(txn))
```

```{r}
table_correlation <- data.frame(Cell_type = NA, Factor = NA, R = NA, p = NA)

for (i in 1:ncol(music)) {
  for (j in 1:ncol(hallmarks)) {
    #print(colnames(music)[i])
    #print(colnames(hallmarks)[j])
    correlation <- cor.test(music[,i], hallmarks[,j], method = 'pearson')
    r <- correlation$estimate
    p <- correlation$p.value
    table_correlation_2 <- data.frame(Cell_type = colnames(music)[i], Factor = colnames(hallmarks)[j], R = r, p = p)
    table_correlation <- rbind(table_correlation, table_correlation_2)
  }
}

table_correlation <- table_correlation[!is.na(table_correlation$Cell_type),]
table_correlation$FDR <- p.adjust(table_correlation$p, method = "fdr")

table_correlation$R[table_correlation$FDR > 0.05 & !is.na(table_correlation$FDR)] <- NA

table_correlation$sign <- 1

table_correlation_1 <- table_correlation
```

```{r}
table_correlation <- data.frame(Cell_type = NA, Factor = NA, R = NA, p = NA)

for (i in 1:ncol(music)) {
  for (j in 1:ncol(txn)) {
    #print(colnames(music)[i])
    #print(colnames(hallmarks)[j])
    correlation <- cor.test(music[,i], txn[,j], method = 'pearson')
    r <- correlation$estimate
    p <- correlation$p.value
    table_correlation_2 <- data.frame(Cell_type = colnames(music)[i], Factor = colnames(txn)[j], R = r, p = p)
    table_correlation <- rbind(table_correlation, table_correlation_2)
  }
}

table_correlation <- table_correlation[!is.na(table_correlation$Cell_type),]
table_correlation$FDR <- p.adjust(table_correlation$p, method = "fdr")

table_correlation$R[table_correlation$FDR > 0.05 & !is.na(table_correlation$FDR)] <- NA

table_correlation$sign <- -1

table_correlation_2 <- table_correlation
```

```{r}
table_correlation <- rbind(table_correlation_1, table_correlation_2)
table_correlation$p <- NULL
table_correlation$FDR <- NULL
```

```{r}
remove <- c("CD4.Memory.T", "CD8.Memory.T", "Early.GMP","Late.GMP", "Naive.T", "NK", "pDC")
```

```{r}
table_correlation <- table_correlation[!table_correlation$Cell_type %in% remove,]
#table_correlation$Factor <- factor(table_correlation$Factor, levels = table_correlation$Factor[!duplicated(table_correlation$Factor)])
```

```{r}
# required, otherwise you cannot use the values as fill
mydat_wide <- table_correlation %>% pivot_wider(names_from = "sign", values_from = "R")
mydat_wide <- data.frame(mydat_wide)
#mydat_wide <- mydat_wide[!is.na(mydat_wide$pos) | !is.na(mydat_wide$neg),]
# making your ordered months factor
mydat_wide$ind <- droplevels(factor(mydat_wide$Cell_type))
# The actual triangle computation
newcoord_up <- make_triangles(mydat_wide$Cell_type, mydat_wide$Factor)
newcoord_down <- make_triangles(mydat_wide$Cell_type, mydat_wide$Factor, point = "down")
# just a dirty trick for renaming
newcoord_down <- newcoord_down %>% dplyr::select(xdown = x, ydown = y)
# you need to repeat each row of your previous data frame 3 times
repdata <- map_df(1:nrow(mydat_wide), function(i) mydat_wide[rep(i, 3), ])
newdata <- bind_cols(repdata, newcoord_up, newcoord_down)
```

```{r}
ggplot(newdata) +
  geom_polygon(aes(x = x, y = y, fill = X1, group = interaction(Factor, ind)), color = "#555555", size = 0.1) +
  scale_fill_gradient2(low = "#2166AC", mid = "#fbf6f0", high = "#B2182B", midpoint = 0, space = "Lab", na.value = "#DDDDDD", guide = "colourbar") +
  ggnewscale::new_scale_fill() +
  geom_polygon(aes(x = xdown, y = ydown, fill = X.1, group = interaction(Factor, ind)), color = "#555555", size = 0.1) +
  scale_fill_gradient2(low = "#2166AC", mid = "#fbf6f0", high = "#B2182B", midpoint = 0, space = "Lab", na.value = "#DDDDDD", guide = "colourbar") +
  scale_x_continuous(breaks = seq_along(unique(mydat_wide$ind)), 
                     labels = unique(levels(mydat_wide$ind))) +
  scale_y_continuous(breaks = seq_along(unique(mydat_wide$Factor)),
                     labels = unique(mydat_wide$Factor))+
  coord_equal()+
  theme(panel.background = element_blank(), # bg of the panel
        panel.grid.major = element_blank(), # get rid of major grid
        panel.grid.minor = element_blank(), # get rid of minor grid
        axis.title=element_blank(),
        panel.grid=element_blank(),
        axis.ticks=element_blank(),
        axis.text.x = element_text(size = 14, angle = 60, hjust=1, colour = "black"),
        axis.text.y = element_text(size = 14, colour = "black"))

ggsave("results/figures/test_triangles_correlation_MOFA_2_corrected.pdf", width = 6, height = 6)
```
